# Generated by Django 5.2.4 on 2025-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('driver', 'Driver'), ('admin', 'Admin'), ('anonim', 'Anonymous')], default='anonim', max_length=10),
        ),
    ]
