# Generated by Django 5.2.4 on 2025-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('busy', 'Band'), ('free', "Bo'sh")], max_length=10, null=True),
        ),
    ]
