# Generated by Django 5.2.4 on 2025-08-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
