# Generated by Django 5.2.4 on 2025-08-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_cargo_cargo_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='weight_tons',
            new_name='weight_kgs',
        ),
    ]
