# Generated by Django 5.2.4 on 2025-08-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_rename_weight_tons_cargo_weight_kgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
