# Generated by Django 5.2.4 on 2025-08-14 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_cargo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='date_available',
            field=models.DateField(default=datetime.datetime(2025, 8, 14, 5, 49, 29, 958625)),
        ),
    ]
