# Generated by Django 5.2.4 on 2025-08-14 07:07

import cargo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_alter_cargo_date_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='date_available',
            field=models.DateField(default=cargo.models.default_available_date),
        ),
    ]
