# Generated by Django 5.2.4 on 2025-08-15 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0009_alter_location_latitude_alter_location_longitude'),
        ('users', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='price_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_kg', models.FloatField()),
                ('volume_m3', models.FloatField()),
                ('has_refrigeration', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('is_busy', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='users.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='cargo.location')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='assigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cargo.cargo')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cargo.truck')),
            ],
        ),
    ]
