# Generated by Django 5.2.4 on 2025-08-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0010_cargo_price_offer_truck_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
